/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_AUDIO_ANALYZER_AUDIO_CONFIG_H_
#define ZEPHYR_AUDIO_ANALYZER_AUDIO_CONFIG_H_

#include <zephyr/sys/util.h>

#define AUDIO_ADC_CHANNEL_ID 5
#define AUDIO_DAC_CHANNEL_ID 0
#define AUDIO_ADC_RESOLUTION 12
#define AUDIO_DAC_RESOLUTION 12
#define AUDIO_ADC_SAMPLE_COUNT BIT(AUDIO_ADC_RESOLUTION)
#define AUDIO_ADC_MIDPOINT (AUDIO_ADC_SAMPLE_COUNT / 2)

#define AUDIO_SAMPLE_RATE_HZ 48000
#define AUDIO_SAMPLE_PERIOD_US (1000000U / AUDIO_SAMPLE_RATE_HZ)

#define AUDIO_FFT_SIZE 256
#define AUDIO_FFT_BITS 8

#endif /* ZEPHYR_AUDIO_ANALYZER_AUDIO_CONFIG_H_ */
